-- Wave 6C: server-authoritative checkout session.
CREATE TABLE checkout_sessions (
  id CHAR(36) NOT NULL,
  customer_id CHAR(36) NOT NULL,
  cart_id CHAR(36) NOT NULL,
  inventory_reservation_id CHAR(36) NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  cart_fingerprint CHAR(64) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  currency CHAR(3) NOT NULL DEFAULT 'INR',
  subtotal_minor INT UNSIGNED NOT NULL,
  shipping_minor INT UNSIGNED NOT NULL DEFAULT 0,
  total_minor INT UNSIGNED NOT NULL,
  shipping_address_id CHAR(36) NULL,
  shipping_address_snapshot JSON NULL,
  serviceability_snapshot JSON NULL,
  shipping_methods_snapshot JSON NULL,
  selected_shipping_method_code VARCHAR(40) NULL,
  reservation_expires_at DATETIME(3) NOT NULL,
  expires_at DATETIME(3) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  cancelled_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_checkout_idempotency (idempotency_key),
  UNIQUE KEY uk_checkout_reservation (inventory_reservation_id),
  KEY idx_checkout_customer_status (customer_id,status,updated_at),
  KEY idx_checkout_cart (cart_id),
  KEY idx_checkout_status_expiry (status,expires_at),
  CONSTRAINT fk_checkout_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE RESTRICT,
  CONSTRAINT fk_checkout_cart FOREIGN KEY (cart_id) REFERENCES carts(id) ON DELETE RESTRICT,
  CONSTRAINT fk_checkout_reservation FOREIGN KEY (inventory_reservation_id) REFERENCES inventory_reservations(id) ON DELETE RESTRICT,
  CONSTRAINT fk_checkout_shipping_address FOREIGN KEY (shipping_address_id) REFERENCES addresses(id) ON DELETE SET NULL,
  CONSTRAINT chk_checkout_status CHECK (status IN ('ACTIVE','READY_FOR_PAYMENT','EXPIRED','CANCELLED')),
  CONSTRAINT chk_checkout_totals CHECK (total_minor = subtotal_minor + shipping_minor)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
