-- Phase 1B — SKU / Catalog Master Rules.
--
-- Introduces backend-authoritative SKU identity:
--   COR-[PRODUCT_TYPE]-[FIT]-[COLOR]-[DESIGN_CODE]-[SIZE]   e.g. COR-TS-O-BLK-ARI-M
--
-- Canonical master data lives in typed reference tables (queryable / validated
-- / auditable), NOT in a settings JSON blob and NOT only in React constants.
-- Design Name + Design Code are admin-entered and owned by the VARIANT (the
-- physical colour-way = one print in practice; the model still lets two
-- variants of one product carry different designs).
--
-- Everything here is ADDITIVE and backward-compatible (brief §30):
--   * new reference tables + seeds (the approved business reference set only)
--   * nullable code FKs on products / product_variants
--   * nullable design_name / design_code on product_variants
--   * skus.sku_kind (LEGACY | CANONICAL) — the sku string column is untouched
--   * sku_aliases — old->new lookup for a future controlled recode (empty now)
--   * invoice_items.sku_id — de-risks the one SKU-string soft join
--     (returns/refundService.#partialCreditNote)
--
-- No column is dropped, no column is made NOT NULL. The free-text
-- products.product_type / products.fit / product_variants.color_name stay for
-- display + backward compatibility.

-- ---- reference tables --------------------------------------------------

CREATE TABLE catalog_product_type_codes (
  id CHAR(36) NOT NULL,
  label VARCHAR(80) NOT NULL,
  code VARCHAR(8) NOT NULL,
  size_family VARCHAR(16) NOT NULL DEFAULT 'APPAREL',
  status VARCHAR(12) NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_catalog_product_type_codes_code (code),
  UNIQUE KEY uq_catalog_product_type_codes_label (label),
  CONSTRAINT chk_ptc_code CHECK (code REGEXP '^[A-Z0-9]{2,8}$'),
  CONSTRAINT chk_ptc_status CHECK (status IN ('ACTIVE','ARCHIVED')),
  CONSTRAINT chk_ptc_family CHECK (size_family IN ('APPAREL','JEANS'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE catalog_fit_codes (
  id CHAR(36) NOT NULL,
  label VARCHAR(80) NOT NULL,
  code VARCHAR(8) NOT NULL,
  status VARCHAR(12) NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_catalog_fit_codes_code (code),
  UNIQUE KEY uq_catalog_fit_codes_label (label),
  CONSTRAINT chk_fc_code CHECK (code REGEXP '^[A-Z0-9]{1,8}$'),
  CONSTRAINT chk_fc_status CHECK (status IN ('ACTIVE','ARCHIVED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE catalog_color_codes (
  id CHAR(36) NOT NULL,
  label VARCHAR(80) NOT NULL,
  code VARCHAR(8) NOT NULL,
  display_hex VARCHAR(9) NULL,
  status VARCHAR(12) NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_catalog_color_codes_code (code),
  UNIQUE KEY uq_catalog_color_codes_label (label),
  CONSTRAINT chk_cc_code CHECK (code REGEXP '^[A-Z0-9]{2,8}$'),
  CONSTRAINT chk_cc_status CHECK (status IN ('ACTIVE','ARCHIVED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---- catalog identity columns ---------------------------------------

ALTER TABLE products
  ADD COLUMN product_type_code_id CHAR(36) NULL AFTER product_type,
  ADD COLUMN fit_code_id CHAR(36) NULL AFTER fit,
  ADD KEY idx_products_product_type_code (product_type_code_id),
  ADD KEY idx_products_fit_code (fit_code_id),
  ADD CONSTRAINT fk_products_product_type_code FOREIGN KEY (product_type_code_id)
    REFERENCES catalog_product_type_codes(id) ON DELETE SET NULL,
  ADD CONSTRAINT fk_products_fit_code FOREIGN KEY (fit_code_id)
    REFERENCES catalog_fit_codes(id) ON DELETE SET NULL;

ALTER TABLE product_variants
  ADD COLUMN color_code_id CHAR(36) NULL AFTER color_hex,
  ADD COLUMN design_name VARCHAR(120) NULL AFTER color_code_id,
  ADD COLUMN design_code VARCHAR(45) NULL AFTER design_name,
  ADD KEY idx_product_variants_color_code (color_code_id),
  ADD CONSTRAINT fk_product_variants_color_code FOREIGN KEY (color_code_id)
    REFERENCES catalog_color_codes(id) ON DELETE SET NULL,
  ADD CONSTRAINT chk_product_variants_design_code
    CHECK (design_code IS NULL OR design_code REGEXP '^[A-Z0-9]{1,45}$');

-- LEGACY = a pre-Phase-1B placeholder SKU string; CANONICAL = generated by the
-- backend SKU authority from the identity components above.
ALTER TABLE skus
  ADD COLUMN sku_kind VARCHAR(12) NOT NULL DEFAULT 'LEGACY' AFTER sku,
  ADD CONSTRAINT chk_skus_kind CHECK (sku_kind IN ('LEGACY','CANONICAL'));

-- ---- controlled SKU recode history (old -> new) --------------------

CREATE TABLE sku_aliases (
  id CHAR(36) NOT NULL,
  sku_id CHAR(36) NOT NULL,
  old_sku VARCHAR(64) NOT NULL,
  new_sku VARCHAR(64) NOT NULL,
  reason VARCHAR(255) NULL,
  actor_staff_id CHAR(36) NULL,
  changed_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_sku_aliases_sku_id (sku_id),
  KEY idx_sku_aliases_old_sku (old_sku),
  CONSTRAINT fk_sku_aliases_sku FOREIGN KEY (sku_id) REFERENCES skus(id) ON DELETE CASCADE,
  CONSTRAINT fk_sku_aliases_actor FOREIGN KEY (actor_staff_id) REFERENCES staff_users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---- SLICE 1 — de-risk the one SKU-string soft join ----------------
-- returns/refundService.#partialCreditNote joins return items to invoice
-- lines by the SKU string. invoice_items had neither sku_id nor
-- order_item_id. Add the immutable relationship; the invoice generator
-- populates it going forward, and the deterministic backfill below covers
-- any pre-existing rows (both snapshots were written together so the string
-- match is safe at backfill time; the runtime join then uses sku_id).
ALTER TABLE invoice_items
  ADD COLUMN sku_id CHAR(36) NULL AFTER sku,
  ADD KEY idx_invoice_items_sku_id (sku_id);

-- ---- seed the APPROVED business reference set only -----------------
-- (business configuration, not mock data — brief §39. No guessed codes.)

INSERT INTO catalog_product_type_codes (id, label, code, size_family) VALUES
  (UUID(), 'T-Shirt', 'TS', 'APPAREL'),
  (UUID(), 'Shirt',   'SH', 'APPAREL'),
  (UUID(), 'Jeans',   'JN', 'JEANS');

INSERT INTO catalog_fit_codes (id, label, code) VALUES
  (UUID(), 'Regular Fit', 'R'),
  (UUID(), 'Slim Fit',    'S'),
  (UUID(), 'Oversize Fit', 'O'),
  (UUID(), 'Relaxed Fit', 'RLX');

INSERT INTO catalog_color_codes (id, label, code, display_hex) VALUES
  (UUID(), 'Black',       'BLK', '#1a1a1a'),
  (UUID(), 'White',       'WHT', '#f5f5f0'),
  (UUID(), 'Beige',       'BEG', '#d9c7a9'),
  (UUID(), 'Lavender',    'LAV', NULL),
  (UUID(), 'Teal',        'TEL', NULL),
  (UUID(), 'Coffee',      'COF', NULL),
  (UUID(), 'Tan',         'TAN', NULL),
  (UUID(), 'Gray',        'GRY', NULL),
  (UUID(), 'Charcoal',    'CHA', NULL),
  (UUID(), 'Navy Blue',   'NVY', NULL),
  (UUID(), 'Light Blue',  'LBL', NULL),
  (UUID(), 'Dreamy Pink', 'PNK', NULL),
  (UUID(), 'Olive',       'OLV', NULL),
  (UUID(), 'Chocolate',   'CHO', NULL),
  (UUID(), 'Blue',        'BLU', NULL);

-- ---- deterministic backfill of code FKs where the existing free-text
--      label is an EXACT match for an approved reference (brief §30 step 3).
--      Ambiguous / unmapped values stay NULL and surface in the Phase 1B
--      migration-readiness report as NEEDS_*_MAPPING. Design codes are NEVER
--      inferred (brief §24).

UPDATE products p
  JOIN catalog_product_type_codes t
    ON t.code = CASE LOWER(p.product_type)
      WHEN 'tshirts' THEN 'TS'
      WHEN 't-shirts' THEN 'TS'
      WHEN 't-shirt' THEN 'TS'
      WHEN 'tshirt' THEN 'TS'
      WHEN 'shirts' THEN 'SH'
      WHEN 'shirt' THEN 'SH'
      WHEN 'jeans' THEN 'JN'
      ELSE NULL END
  SET p.product_type_code_id = t.id
  WHERE p.product_type_code_id IS NULL;

UPDATE products p
  JOIN catalog_fit_codes f
    ON f.code = CASE LOWER(p.fit)
      WHEN 'regular fit' THEN 'R'
      WHEN 'regular' THEN 'R'
      WHEN 'slim fit' THEN 'S'
      WHEN 'slim' THEN 'S'
      WHEN 'oversize fit' THEN 'O'
      WHEN 'oversized fit' THEN 'O'
      WHEN 'oversize' THEN 'O'
      WHEN 'oversized' THEN 'O'
      WHEN 'relaxed fit' THEN 'RLX'
      WHEN 'relaxed' THEN 'RLX'
      ELSE NULL END
  SET p.fit_code_id = f.id
  WHERE p.fit_code_id IS NULL;

UPDATE product_variants v
  JOIN catalog_color_codes c ON LOWER(c.label) = LOWER(v.color_name)
  SET v.color_code_id = c.id
  WHERE v.color_code_id IS NULL AND v.color_name IS NOT NULL AND v.color_name <> '';

-- ---- backfill invoice_items.sku_id (no rows today; safety net) ------
UPDATE invoice_items ii
  JOIN invoices inv ON inv.id = ii.invoice_id
  JOIN order_items oi ON oi.order_id = inv.order_id AND oi.sku = ii.sku
  SET ii.sku_id = oi.sku_id
  WHERE ii.sku_id IS NULL
    AND (SELECT COUNT(DISTINCT oi2.sku_id) FROM order_items oi2 WHERE oi2.order_id = inv.order_id AND oi2.sku = ii.sku) = 1;
