import { InlineAlert } from '../../../components/feedback/InlineAlert.jsx';
import { adminApi } from '../../../api/adminApi.js';
import { useSkuOptions } from '../skuIdentity.js';
import { CodeSelect } from './CodeSelect.jsx';

// Form-oriented SKU identity picker for the Basic-information section. It does
// NOT persist on its own — the parent form includes productTypeCodeId /
// fitCodeId in its create/update call. `locked` disables the selects when the
// product has SKUs with order/inventory history (the codes are then frozen).
export function SkuIdentityFields({ value, onChange, disabled = false, locked = false }) {
  const { data: options, status, reload } = useSkuOptions();
  const types = (options?.productTypes || []).filter((t) => t.status === 'ACTIVE');
  const fits = (options?.fits || []).filter((f) => f.status === 'ACTIVE');

  const createType = async (body) => { const c = await adminApi.catalog.createTypeCode(body); reload(); return c; };
  const createFit = async (body) => { const c = await adminApi.catalog.createFitCode(body); reload(); return c; };

  const ptCode = types.find((t) => t.id === value.productTypeCodeId)?.code;
  const fitCode = fits.find((f) => f.id === value.fitCodeId)?.code;

  return (
    <fieldset className="editor-form__fieldset">
      <legend>SKU identity</legend>
      {status === 'error' && <InlineAlert tone="warning">Could not load the SKU code list.</InlineAlert>}
      <div className="editor-form__grid">
        <CodeSelect
          id="sku-type-code" label="Product type code"
          hint="A short code that identifies the product type, e.g. TSH for T-Shirt, HOD for Hoodie."
          value={value.productTypeCodeId} onChange={(v) => onChange({ ...value, productTypeCodeId: v || '' })}
          options={types} disabled={disabled || locked} onCreate={createType} withFamily
        />
        <CodeSelect
          id="sku-fit-code" label="Fit code"
          hint="A short code that identifies the fit, e.g. OVR for Oversize, REG for Regular, RLX for Relaxed."
          value={value.fitCodeId} onChange={(v) => onChange({ ...value, fitCodeId: v || '' })}
          options={fits} disabled={disabled || locked} onCreate={createFit}
        />
      </div>
      <p className="sku-identity__prefix">
        SKU prefix: <code>{['COR', ptCode || '·', fitCode || '·'].join('-')}</code>
        <span className="text-faint"> — colour, design and size are added per variant. The full SKU is generated by the backend.</span>
      </p>
      {locked && (
        <InlineAlert tone="info">Type and fit codes are locked — this product has SKUs with order or inventory history.</InlineAlert>
      )}
    </fieldset>
  );
}

export default SkuIdentityFields;
