// Wave 8I §68 — the stable, provider-neutral error vocabulary the OPERATIONAL
// plane records and shows. Adapters already raise `ProviderError` with the
// codes in platform/shared/providerError.js; this maps those (and a few raw
// shapes) onto the fixed set the CMS / attempts log speak.

export const NORMALIZED_ERROR = Object.freeze({
  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',
  PROVIDER_MISCONFIGURED: 'PROVIDER_MISCONFIGURED',
  PROVIDER_TIMEOUT: 'PROVIDER_TIMEOUT',
  PROVIDER_RATE_LIMITED: 'PROVIDER_RATE_LIMITED',
  PROVIDER_VALIDATION_FAILED: 'PROVIDER_VALIDATION_FAILED',
  PROVIDER_AUTH_FAILED: 'PROVIDER_AUTH_FAILED',
  PROVIDER_RESULT_UNKNOWN: 'PROVIDER_RESULT_UNKNOWN',
});

const MAP = new Map([
  ['RATE_LIMITED', NORMALIZED_ERROR.PROVIDER_RATE_LIMITED],
  ['PROVIDER_RATE_LIMITED', NORMALIZED_ERROR.PROVIDER_RATE_LIMITED],
  ['PROVIDER_AUTH_FAILED', NORMALIZED_ERROR.PROVIDER_AUTH_FAILED],
  ['PROVIDER_UNAVAILABLE', NORMALIZED_ERROR.PROVIDER_UNAVAILABLE],
  ['PROVIDER_TIMEOUT', NORMALIZED_ERROR.PROVIDER_TIMEOUT],
  ['PROVIDER_RESULT_UNKNOWN', NORMALIZED_ERROR.PROVIDER_RESULT_UNKNOWN],
  ['PROVIDER_VALIDATION_FAILED', NORMALIZED_ERROR.PROVIDER_VALIDATION_FAILED],
  ['PROVIDER_RESPONSE_INVALID', NORMALIZED_ERROR.PROVIDER_VALIDATION_FAILED],
  ['PROVIDER_NOT_CONFIGURED', NORMALIZED_ERROR.PROVIDER_MISCONFIGURED],
  ['PROVIDER_MISCONFIGURED', NORMALIZED_ERROR.PROVIDER_MISCONFIGURED],
]);

/** @param {unknown} err a ProviderError, an Error, or a bare code string */
export function normalizeErrorCode(err) {
  if (!err) return null;
  const code = typeof err === 'string' ? err : (err.code || err.name);
  if (!code) return NORMALIZED_ERROR.PROVIDER_UNAVAILABLE;
  return MAP.get(code) || (Object.values(NORMALIZED_ERROR).includes(code) ? code : NORMALIZED_ERROR.PROVIDER_UNAVAILABLE);
}
